spring:
datasource:
 #   url: jdbc:postgresql://localhost:5432/your_database_name
  #  username: your_db_user
   # password: your_db_password
    #driver-class-name: org.postgresql.Driver
  jpa:
   # database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # 데이터베이스가 없을 때 오류 방지