spring:
    application:
      name: company-service  # Eureka에 등록될 서비스명

      eureka:
        client:
          service-url:
            defaultZone: http://localhost:19090/eureka/  # Eureka Server 주소
        instance:
          prefer-ip-address: true  # IP 기반 서비스 검색

datasource:
 #   url: jdbc:postgresql://localhost:5432/your_database_name
  #  username: your_db_user
   # password: your_db_password
    #driver-class-name: org.postgresql.Driver
  jpa:
   # database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # 데이터베이스가 없을 때 오류 방지



