spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
#    data:
#      redis:
#        host: localhost
#        port: 6379


    properties:
      show-sql: true
      format_sql: true
      highlight_sql: true

logging:
  level:
    org.hibernate.SQL: debug #logger
    org.hibernate.orm.jdbc.bind: trace #?? ???? ?? ???
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
